---
- name: Deploy AltSchool Catalog
  hosts: webservers
  become: yes

  tasks:
    - name: Install Nginx and update_cache
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy all related files to web root with index.html
      copy:
        src: /home/vagrant/alt_project/Exam_Project/
        dest: /var/www/html/


    - name: Replace placeholder with actual IP
      replace:
        path: /var/www/html/index.html
        regexp: 'INSTANCE_IP_PLACEHOLDER'
        replace: "{{ ansible_default_ipv4.address }}"

    - name: Replace placeholder with actual hostname
      replace:
        path: /var/www/html/index.html
        regexp: 'INSTANCE_HOSTNAME_PLACEHOLDER'
        replace: "{{ ansible_hostname }}"

