---
- name: Setup Basic Apache Web Server on AWS
  hosts: webservers
  become: yes

  tasks:
    - name: Install Apache
      ansible.builtin.package:
        name: apache2
        state: present


    - name: Deploy custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "Hi! My name is Olaoluwa, Hello from Ansible\n"
        owner: root
        group: root
        mode: '0644'

    - name: Set timezone to Africa/Lagos
      ansible.builtin.command: timedatectl set-timezone Africa/Lagos

    - name: Ensure Apache is started and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

    - name: Ensure UFW allows port 80 
      ansible.builtin.ufw:
        rule: allow
        port: 80
        proto: tcp

